/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCPROG_H_RPCGEN
#define _RPCPROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define RPCPROG 99
#define RPCVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETRPC 1
extern  char ** getrpc_1(char **, CLIENT *);
extern  char ** getrpc_1_svc(char **, struct svc_req *);
extern int rpcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETRPC 1
extern  char ** getrpc_1();
extern  char ** getrpc_1_svc();
extern int rpcprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCPROG_H_RPCGEN */
